/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Analisador;


import Clases.Errores;
import Clases.Tokens_L;
import Clases.arbol;

import Lista.Lista_errores;
import Lista.Lista_tokens;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.List;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.Lexer;
import java_cup.runtime.Symbol;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;




/**
 *
 * @author Usuario
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    Lista_errores lista_errores = new Lista_errores();
    Lista_tokens lista_token =  new Lista_tokens();
    Tokens_L tokens_L;
    Errores error;
    int contador = 2;
    int conteo_errores = 1;
    int conteo_tokens = 1;
    
    
    

    
    
    
    public FrmPrincipal() {
        
        initComponents();
        contador = 2;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnAbrirArchivo = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jbConsola = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 51));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Archivo 1", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        btnCrear.setBackground(new java.awt.Color(0, 102, 153));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("+");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnAbrirArchivo.setBackground(new java.awt.Color(0, 102, 153));
        btnAbrirArchivo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAbrirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirArchivo.setText("Arbir Archivo");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        btnEjecutar.setBackground(new java.awt.Color(0, 102, 153));
        btnEjecutar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnEjecutar.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(153, 0, 0));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAbrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjecutar)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jbConsola.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jbConsola.setText("Consola");

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane2.setViewportView(txtConsola);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsola)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbConsola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        
        JPanel panel4 = new JPanel();

        // Crear un JTextArea editable con tamaño predeterminado
        JTextArea textArea1 = new JTextArea();
        textArea1.setEditable(true);
        
        // Crear un JScrollPane y agregar el JTextArea a él
        JScrollPane scoo = new JScrollPane(textArea1);
        
        // Establecer el tamaño preferido del JScrollPane
        scoo.setPreferredSize(new Dimension(523, 200));

        // Agregar el JScrollPane al panel
        panel4.add(scoo);

        
        

        // Agregar el panel al JTabbedPane
        jTabbedPane1.addTab("Archivo " + contador, panel4);
        contador++;
        
        
        
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        
        int index = jTabbedPane1.getSelectedIndex();
        
        if(index > -1){
             JPopupMenu popMenu =  new JPopupMenu();
            JMenuItem eliminar= new JMenuItem("Eliminar");
            eliminar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jTabbedPane1.remove(index);
                }
            });

            JMenuItem guardar =  new JMenuItem("Guardar");
            guardar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    guardar();

                }
            });

            

            popMenu.add(eliminar);
            popMenu.add(guardar);
            
            popMenu.show(jTabbedPane1, evt.getX(), evt.getY()+15);
                
            
        }
                

    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos DF", "df");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false); // Evitar que se acepten todos los tipos de archivo

        int option = chooser.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            String extension = getFileExtension(archivo);
            if (extension.equalsIgnoreCase("df")) {
                // El archivo seleccionado tiene la extensión correcta (.df)
                try {
                    String fileName = archivo.toPath().getFileName().toString();
                    String fileNameWithoutExtension = fileName.replaceFirst("[.][^.]+$", "");
                    String St = new String(Files.readAllBytes(archivo.toPath()));

                    JTextArea textArea1 = new JTextArea();
                    
                    textArea1.setEditable(true);
                    textArea1.setText(St);
                    
                    JScrollPane scoo =  new JScrollPane(textArea1);
                    scoo.setPreferredSize(new Dimension(523, 200));

                    JPanel panel = new JPanel();
                    panel.add(scoo);
                    jTabbedPane1.addTab(fileNameWithoutExtension, panel);
                } catch (IOException e) {
                    e.printStackTrace();
                    // Manejar la excepción
                }
            } else {
                // Mostrar mensaje de extensión incorrecta
                JOptionPane.showMessageDialog(null, "Seleccione un archivo con extensión .df", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        lista_token.limpiar();
        lista_errores.limpiar();
        
        try {
            
            
            String texto = obtenerTextArea();
            LexerCup scan = new LexerCup(new StringReader(texto));
            Parser parser = new Parser(scan);
            arbol raiz = (arbol)parser.parse().value;
            raiz.printArbol(raiz);
            //parser.parse();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        


       
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se creo los Reportes correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        lista_errores.reportesErrores();
        lista_token.reporte();
        
        
    }//GEN-LAST:event_btnReportesActionPerformed

    private void jTabbedPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseExited
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTabbedPane1MouseExited

    
    public String obtenerTextArea(){
        int index = jTabbedPane1.getSelectedIndex();
        
        if(index != -1){
            
            Component sectedComponent =  jTabbedPane1.getComponentAt(index);
            
            if(sectedComponent instanceof Container){
                JTextArea textArea = findJTextArea(sectedComponent);
                
                if(textArea != null){
                    String content = textArea.getText();
                    
                    return content.toLowerCase();
                   
                }
                
            }
        }
        return null;
    }
    
    private void guardar() {
        int index = jTabbedPane1.getSelectedIndex();

        if (index != -1) {
            // Obtener el nombre de la pestaña seleccionada
            String tabTitle = jTabbedPane1.getTitleAt(index);

            // Obtener el componente (panel) de la pestaña actual
            Component selectedComponent = jTabbedPane1.getComponentAt(index);

            // Verificar si el componente es un contenedor válido
            if (selectedComponent instanceof Container) {
                JTextArea textArea = findJTextArea(selectedComponent);

                if (textArea != null) {
                    // Obtener el contenido del JTextArea
                    String content = textArea.getText();

                    // Definir la ruta y el nombre del archivo
                    String filePath = "C:\\Users\\Usuario\\Desktop\\Usac\\" + tabTitle + ".df";

                    try {
                        File file = new File(filePath);
                        BufferedWriter writer = new BufferedWriter(new FileWriter(file));
                        writer.write(content);
                        writer.close();
                        JOptionPane.showMessageDialog(null, "Archivo guardado exitosamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                    } catch (IOException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error al guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo encontrar el JTextArea en la pestaña seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    // Método para encontrar un JTextArea dentro de un contenedor
    private JTextArea findJTextArea(Component container) {
        if (container instanceof JTextArea) {
            return (JTextArea) container;
        }

        if (container instanceof JScrollPane) {
            JScrollPane scrollPane = (JScrollPane) container;
            Component viewportView = scrollPane.getViewport().getView();

            if (viewportView instanceof JTextArea) {
                return (JTextArea) viewportView;
            }
        }

        if (container instanceof Container) {
            Component[] components = ((Container) container).getComponents();

            for (Component comp : components) {
                JTextArea textArea = findJTextArea(comp);
                if (textArea != null) {
                    return textArea;
                }
            }
        }

        return null;
    }
    




    private String getFileExtension(File file) {
    String extension = "";
    String fileName = file.getName();
    int dotIndex = fileName.lastIndexOf('.');
    if (dotIndex > 0 && dotIndex < fileName.length() - 1) {
        extension = fileName.substring(dotIndex + 1).toLowerCase();
    }
    return extension;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jbConsola;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}
