
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Reservemenor = 11;
  public static final int G_label = 17;
  public static final int OPE = 14;
  public static final int OPA = 12;
  public static final int End = 3;
  public static final int Coma = 26;
  public static final int Llave_c = 33;
  public static final int Arr = 5;
  public static final int Llave_a = 32;
  public static final int G_exec = 23;
  public static final int Var = 4;
  public static final int Column = 8;
  public static final int Arroba = 42;
  public static final int A_mod = 13;
  public static final int Punto = 39;
  public static final int Parent_c = 38;
  public static final int Parent_a = 37;
  public static final int Console = 6;
  public static final int Division = 29;
  public static final int G_tituloy = 21;
  public static final int Cadena = 10;
  public static final int G_titulox = 20;
  public static final int Parentesis_c = 31;
  public static final int Parentesis_a = 30;
  public static final int P_coma = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Reserve = 35;
  public static final int G_ejey = 19;
  public static final int G_titulo = 16;
  public static final int G_ejex = 18;
  public static final int Tipo = 9;
  public static final int C_dobles_c = 41;
  public static final int G_tipo_grafica = 15;
  public static final int Print = 7;
  public static final int ERROR = 46;
  public static final int C_dobles_a = 40;
  public static final int Doble_puntos = 43;
  public static final int Dos_puntos = 34;
  public static final int G_values = 22;
  public static final int Identificador = 44;
  public static final int Resta = 27;
  public static final int Multiplicacion = 28;
  public static final int Numero = 45;
  public static final int Program = 2;
  public static final int Suma = 25;
  public static final int Igual = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Program",
  "End",
  "Var",
  "Arr",
  "Console",
  "Print",
  "Column",
  "Tipo",
  "Cadena",
  "Reservemenor",
  "OPA",
  "A_mod",
  "OPE",
  "G_tipo_grafica",
  "G_titulo",
  "G_label",
  "G_ejex",
  "G_ejey",
  "G_titulox",
  "G_tituloy",
  "G_values",
  "G_exec",
  "Igual",
  "Suma",
  "Coma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Dos_puntos",
  "Reserve",
  "P_coma",
  "Parent_a",
  "Parent_c",
  "Punto",
  "C_dobles_a",
  "C_dobles_c",
  "Arroba",
  "Doble_puntos",
  "Identificador",
  "Numero",
  "ERROR"
  };
}

